#
# Copyright (c) 2020 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Keep application config minimal and let the Sokosti board defconfig
# select the correct base system options.

CONFIG_GPIO=y
CONFIG_SPI=y

CONFIG_NRFX_TIMER=y
CONFIG_NRFX_GPIOTE=y
CONFIG_NRFX_GPPI=y

CONFIG_PRINTK=y

CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y